package com.metalSpring.model.enums;

public enum PedidoStatus {
    PENDENTE,
    AGUARDANDO_NEGOCIACAO,
    PAGAMENTO_LIBERADO,
    PAGAMENTO_PENDENTE,
    PAGAMENTO_INFORMADO_CLIENTE,
    PAGAMENTO_CONFIRMADO,
    EM_PREPARACAO,
    CONCLUIDO,
    CONFIRMADO,
    EM_SEPARACAO,
    ENVIADO,
    ENTREGUE,
    CANCELADO
}
