spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/metalsc}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:senai}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:validate}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}

app.admin.enabled=${ADMIN_ENABLED:false}
